# Generated by Django 5.0.1 on 2025-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['user', '-created_at'], name='core_dailye_user_id_25bad7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='core_task_user_id_0440f1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', '-completed_at'], name='core_task_user_id_55d27e_idx'),
        ),
    ]
