# Generated by Django 5.0.1 on 2025-10-02 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyentry_core_dailye_user_id_25bad7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('houses', models.JSONField(default=dict)),
                ('planets', models.JSONField(default=dict)),
                ('aspects', models.JSONField(default=list)),
                ('interpretation', models.TextField()),
                ('personality_reading', models.TextField(blank=True)),
                ('career_reading', models.TextField(blank=True)),
                ('relationships_reading', models.TextField(blank=True)),
                ('life_purpose_reading', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natal_charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Натальная карта',
                'verbose_name_plural': 'Натальные карты',
                'ordering': ['-created_at'],
            },
        ),
    ]
