# Generated by Django 5.0.1 on 2025-10-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_natalchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacprofile',
            name='sign_experience',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='zodiacprofile',
            name='sign_levels',
            field=models.JSONField(default=dict),
        ),
    ]
