# Generated by Django 5.0.1 on 2025-10-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_zodiacprofile_sign_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
